[build]
  publish = "public"
  command = "npm run build"
[build.environment]
  YARN_VERSION = "1.9.4"
  YARN_FLAGS = "--no-ignore-optional"
[[redirects]]
  from = "http://www.fredwu.me/*"
  to = "http://fredwu.me/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://www.fredwu.me/*"
  to = "https://fredwu.me/:splat"
  status = 301
  force = true
